services:
  app.menu_builder:
    class: MainBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory", @doctrine.orm.entity_manager]

  app.main_menu:
    class: Knp\Menu\MenuItem
    factory: ["@app.menu_builder", createMainMenu]
    tags:
      - { name: knp_menu.menu, alias: main }

  admin.post:
    class: MainBundle\Admin\CategoryPostAdmin
    arguments: [~, MainBundle\Entity\CategoryPost, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Статейник, label: Категории }

  admin.video_report:
    class: MainBundle\Admin\PostAdmin
    arguments: [~, MainBundle\Entity\Post, SonataAdminBundle:CRUD]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Статейник, label: Посты }
